language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
      
notifications:
  email:
    recipients:
      - dev@speedment.com
    on_success: never  # default: change
    on_failure: always # default: always
